# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller:
        enabled:              '%kernel.debug%'
        profiler:             false
#    read_from:            '%assetic.read_from%'
    write_to:             '%kernel.root_dir%/../web'
    java: /usr/bin/java
    node: /usr/bin/node
    node_paths:
        - "%kernel.root_dir%/../node_modules"  
        - /usr/lib/node_modules
        - /usr/lib/nodejs
        - /usr/share/javascript
    ruby: /usr/bin/ruby
    filters:
#        autoprefixer: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        coffee: ~
        compass:
            bin: /usr/local/bin/compass
        csscachebusting: ~
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed-0.4.5.jar"
        cssimport: ~
        cssmin: ~
        cssrewrite: ~
        dart:
            bin: /usr/lib/dart/bin/dart2js
        emberprecompile:
            bin: /usr/bin/ember
        gss:
            jar: "%kernel.root_dir%/Resources/java/closure-stylesheets-library.jar"
        handlebars: ~
        jpegoptim: ~
        jpegtran: ~
        jsmin: ~
        jsminplus: ~
        jsqueeze: ~
        less:
            bin: "%kernel.root_dir%/../node_modules/.bin/lessc"
        minifycsscompressor: ~
        optipng: ~
        packager: ~
        packer: ~
        phpcssembed: ~
        pngout:
            bin: "%kernel.root_dir%/../node_modules/.bin/pngout"
#            bin: "%kernel.root_dir%/../bin/pngout"
        reactjsx:
            bin: /usr/bin/jsx
        roole: ~
        sass:
            bin: "%kernel.root_dir%/../node_modules/.bin/node-sass"
#            bin: /usr/local/bin/sass
        scss: ~
        sprockets:
            lib: /usr/local/bin/sprockets
        typescript: ~
        uglifycss:
            # on utilise le uglifycss installé localement
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifycss"
        uglifyjs2:
            # on utilise le uglifyjs installé localement
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifyjs"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
    bundles:
        - SasedevSharedBundle
        - IlcfrancePassportstagiaireResBundle

    assets:


# css

        css_min_fontawesome_less:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/less/font-awesome.less'
            filters:
                - less
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/font-awesome.min.css'

        css_min_glyphicons_less:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/less/glyphicons.less'
            filters:
                - less
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/glyphicons.min.css'

        css_min_select2:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/select2/dist/css/select2.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/select2.min.css'

        css_sasedevtpl_less:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/less/app.less'
            filters:
                - less
                - cssrewrite
            combine: true
            output: 'res/css/sasedevtpl.css'

        css_min_sasedevtpl_less:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/less/app.less'
            filters:
                - less
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/sasedevtpl.min.css'

        css_min_datatables_net_bs:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-bs/css/dataTables.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.min.css'

        css_min_datatables_net_bs_autofill:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-autofill-bs/css/autoFill.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.autoFill.min.css'

        css_min_datatables_net_bs_buttons:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-buttons-bs/css/buttons.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.buttons.min.css'

        css_min_datatables_net_bs_colReorder:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-colreorder-bs/css/colReorder.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.colReorder.min.css'

        css_min_datatables_net_bs_fixedHeader:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.fixedHeader.min.css'

        css_min_datatables_net_bs_fixedColumns:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-fixedcolumns-bs/css/fixedColumns.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.fixedColumns.min.css'

        css_min_datatables_net_bs_keyTable:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-keytable-bs/css/keyTable.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.keyTable.min.css'

        css_min_datatables_net_bs_responsive:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-responsive-bs/css/responsive.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.responsive.min.css'

        css_min_datatables_net_bs_scroller:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-scroller-bs/css/scroller.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.scroller.min.css'

        css_min_datatables_net_bs_select:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-select-bs/css/select.bootstrap.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/dataTables.bs.select.min.css'

        css_min_cropper:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/cropper/dist/cropper.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/cropper.min.css'

        css_min_fileinput:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-fileinput/css/fileinput.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/fileinput.min.css'
            

        css_min_app:
            inputs:
                - '@css_min_fontawesome_less'
                - '@css_min_glyphicons_less'
                - '@css_min_select2'
                - '@css_min_sasedevtpl_less'
                - '@css_min_datatables_net_bs'
                - '@css_min_datatables_net_bs_autofill'
                - '@css_min_datatables_net_bs_buttons'
                - '@css_min_datatables_net_bs_colReorder'
                - '@css_min_datatables_net_bs_fixedHeader'
                - '@css_min_datatables_net_bs_fixedColumns'
                - '@css_min_datatables_net_bs_keyTable'
                - '@css_min_datatables_net_bs_responsive'
                - '@css_min_datatables_net_bs_scroller'
                - '@css_min_datatables_net_bs_select'
                - '@css_min_cropper'
                - '@css_min_fileinput'
            filters:
                - less
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'res/css/app.min.css'
            

# js html5html5shiv + respond

        js_min_html5shiv:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/html5shiv/dist/html5shiv.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/html5shiv.min.js'

        js_min_respond:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/respond/src/matchmedia.polyfill.js'
                - '%kernel.root_dir%/../web/res/bower_components/respond/src/matchmedia.addListener.js'
                - '%kernel.root_dir%/../web/res/bower_components/respond/src/respond.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/respond.min.js'

        js_min_html5respond:
            inputs:
                - '@js_min_html5shiv'
                - '@js_min_respond'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/html5shiv.respond.min.js'

        js_min_hinclude:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/hinclude/hinclude.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/hinclude.min.js'

        js_min_jquery:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery/dist/jquery.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/jquery.min.js'

        js_min_jquery_form:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery-form/src/jquery.form.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/jquery.form.min.js'

        js_min_cropper:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/cropper/dist/cropper.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/jquery.cropper.min.js'

        js_min_bootstrap:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/bootstrap/dist/js/bootstrap.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/bootstrap.min.js'

        js_min_iCheck:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/iCheck/icheck.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/iCheck.min.js'

        js_min_iCheck_init:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/js/iCheck_init.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/iCheck_init.min.js'

        js_min_select2:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/select2/dist/js/select2.full.js'
#                - '%kernel.root_dir%/../web/res/bower_components/select2/dist/js/i18n/*.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/select2.min.js'

        js_min_select2_init:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/js/select2_init.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/select2_init.min.js'

        js_min_bootstrap_duallistbox:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-duallistbox/src/jquery.bootstrap-duallistbox.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/bootstrap.duallistbox.min.js'

        js_min_duallistbox_init:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/js/duallistbox_init.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/duallistbox_init.min.js'

        js_min_moment:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/moment/min/moment-with-locales.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/moment.min.js'

        js_min_bootstrap_datetimepicker:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/bootstrap.datetimepicker.min.js'

        js_min_datetimepicker_init:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/js/datetimepicker_init.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/datetimepicker_init.min.js'

        js_min_blueimp_canvas_to_blob:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/blueimp-canvas-to-blob/js/canvas-to-blob.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/blueimp-canvas-to-blob.min.js'

        js_min_bootstrap_fileinput:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-fileinput/js/fileinput.js'
#                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-fileinput/js/locales/*.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/bootstrap.fileinput.min.js'

        js_min_fileinput_init:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/js/fileinput_init.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/fileinput_init.min.js'

        js_min_jquery_slimscroll:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery-slimscroll/jquery.slimscroll.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/jquery.slimscroll.min.js'

        js_min_dashboard:
            inputs:
                - '%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/ResBundle/Resources/js/dashboard.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/dashboard.min.js'

        js_min_jquery_datatables_net:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net/js/jquery.dataTables.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/dataTables.jquery.min.js'

        js_min_datatables_net_bs:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-bs/js/dataTables.bootstrap.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/dataTables.bs.min.js'

        js_min_tinymce:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/tinymce/tinymce.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/tinymce4.min.js'

        js_min_jquery_tinymce:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/tinymce/jquery.tinymce.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/jquery.tinymce4.min.js'

# js apps

        js_min_secure:
            inputs:
                - '@js_min_jquery'
                - '@js_min_bootstrap'
                - '@js_min_iCheck'
                - '@js_min_iCheck_init'
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/secure.ilc.min.js'

        js_min_app:
            inputs:
                - '@js_min_jquery'
                - '@js_min_jquery_datatables_net'
                - '@js_min_bootstrap'
                - '@js_min_datatables_net_bs'
                - '@js_min_iCheck'
                - '@js_min_select2'
                - '@js_min_bootstrap_duallistbox'
                - '@js_min_moment'
                - '@js_min_bootstrap_datetimepicker'
                - '@js_min_blueimp_canvas_to_blob'
                - '@js_min_bootstrap_fileinput'
                - '@js_min_jquery_slimscroll'
                - '@js_min_dashboard'
                - '@js_min_iCheck_init'
                - '@js_min_select2_init'
                - '@js_min_duallistbox_init'
                - '@js_min_datetimepicker_init'
                - '@js_min_fileinput_init'
                - '@js_min_tinymce'
                
            filters:
                - uglifyjs2
            combine: true
            output: 'res/js/app.ilc.min.js'


