# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  "%database_charset%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    IlcfrancePassportstagiaireDataBundle:
                         type: annotation
                         dir: "%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/DataBundle/Entity"
                         prefix: Ilcfrance\Passportstagiaire\DataBundle\Entity
                         alias: IlcfrancePassportstagiaireDataBundle
                naming_strategy: doctrine.orm.naming_strategy.underscore
                metadata_cache_driver: 
                    type: service
                    id: doctrine.cache.predis
                query_cache_driver: 
                    type: service
                    id: doctrine.cache.predis
                result_cache_driver: 
                    type: service
                    id: doctrine.cache.predis
                second_level_cache:
                    enabled: true
                    log_enabled: true
                    region_cache_driver:
                        type: service
                        id: doctrine.cache.predis
                    region_lock_lifetime: 3000
                    region_lifetime: 3000
                    regions:
                        region_Document:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Locale:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Locale_users:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Program:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Role:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Role_parents:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Role_childs:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Role_users:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Trainee:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_Trainee_records:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_TraineeRecord:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_TraineeRecord_trainee:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_TraineeRecord_teacher:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_TraineeRecord_docs:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_TraineeRecordDocument:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_TraineeRecordDocument_traineeRecord:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_User:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_User_locale:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_User_picture:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_User_userRoles:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_User_records:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_UserPicture:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis
                        region_UserPicture_id:
                            lifetime: 3000
                            cache_driver:
                                type: service
                                id: doctrine.cache.predis

