# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  "%database_charset%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    IlcfrancePassportstagiaireDataBundle:
                         type: annotation
                         dir: "%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/DataBundle/Entity"
                         prefix: Ilcfrance\Passportstagiaire\DataBundle\Entity
                         alias: IlcfrancePassportstagiaireDataBundle
            mig:
                connection: default
                mappings:
                    IlcfrancePassportstagiaireDataBundle:
                         type: annotation
                         dir: "%kernel.root_dir%/../src/Ilcfrance/Passportstagiaire/DataBundle/Entity"
                         prefix: Ilcfrance\Passportstagiaire\DataBundle\Entity
                         alias: IlcfrancePassportstagiaireDataBundle
                metadata_cache_driver: apcu
                query_cache_driver: apcu
                result_cache_driver: apcu
                second_level_cache:
                    enabled: true
                    log_enabled: true
                    region_cache_driver: apcu
                    region_lock_lifetime: 20
                    region_lifetime: 86400
