# Syfony2 framework
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
        hinclude_default_template: 'SasedevSharedBundle::hinclude.html.twig'
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  snc_redis.session.handler # session.mongo.handler
        name: "ILCFrancePassportstagiaire"
        cookie_lifetime: 2592000 # optional, it is set to 30 days here #3600
        cookie_domain: ".%domain%"
#        save_path:   '%kernel.cache_dir%/sessions'
        gc_probability: 0
        gc_maxlifetime: 2592000 # optional, it is set to 30 days here #7200
    fragments: { path: /_fragment }
    http_method_override: true
    assets: ~
    cache:
        app: cache.adapter.redis
        default_redis_provider: "%redis_dns%"
    serializer:
        enable_annotations: true
        cache: serializer.mapping.cache.apc
