# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    hide_user_not_found:  true

    encoders:
        Ilcfrance\Passportstagiaire\DataBundle\Entity\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000
            key_length:           40

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            entity:
                class: "IlcfrancePassportstagiaireDataBundle:User"
#                property: username
#                manager_name:       ~

        chain_provider:
            chain:
                providers: ["user_provider"]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt))/
            security: false
            anonymous:  true
        resources:
            pattern:  ^/(css|js|images|img|imgs|fonts|webfonts|assets|bundles|res)/
            security: false
            anonymous:  true
        secoff:
            pattern:  ^/(logout|login|login_check|lostId|lostPassword|generateNewPassword)/
            security: false
            anonymous:  true

        main:
            pattern:      .*
#            host: "%domain%"
            provider: chain_provider
            form_login:
                login_path:     /login
                check_path:     /login_check
                post_only:      true
                username_parameter:     "LoginForm[username]"
                password_parameter:     "LoginForm[password]"
                target_path_parameter:  "LoginForm[target_path]"
                default_target_path: /myProfile
                always_use_default_target_path: false
                use_referer:    true
                use_forward:    false
#                intention: authentication
                require_previous_session: true
                remember_me:    true
#                success_handler: login.listener
            logout:
                path:   /logout
                target: /
                invalidate_session: true
#                target: '%schemes%://%domain%/'
#                success_handler: logout_listener
            remember_me:
                secret: "%secret%"
                name: ILCFrancePassportstagiaireSec
                lifetime: 2592000 # optional, it is set to 30 days here
                path: ^/
#                domain: "%domain%"
                always_remember_me: true
                remember_me_parameter: "LoginForm[remember_me]"
            security: true
            anonymous:    true
            logout_on_user_change: true
    access_control:
        # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/lostId, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/lostPassword, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/generateNewPassword.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ["ROLE_USER", "IS_AUTHENTICATED_FULLY"] }
    access_denied_url: /login
