services:
    Twig\Extensions\ArrayExtension: ~
    Twig\Extensions\DateExtension: ~
    Twig\Extensions\I18nExtension: ~
    Twig\Extensions\IntlExtension: ~
    Twig\Extensions\TextExtension: ~
    
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'SasedevSharedBundle::form.html.twig'
    globals:
        schemes: "%schemes%"
        domain: "%domain%"
        default_locale: "%locale%"
        sitename: "%sitename%"
        timezone:               "Europe/Paris"
