imports:
    - { resource: parameters.yml }
    - { resource: parameters_prod.yml }
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_%kernel.environment%.yml"
        strict_requirements: true

monolog:
    handlers:
        syslog_error:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_error.log"
            level: error
        syslog_info:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_info.log"
            channels: ["!event", "!doctrine"]
            level: info
        syslog_debug:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_debug.log"
            level: debug
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
