services:
#    ilcfrance_passportstagiaire_data.example:
#        class: Ilcfrance\Passportstagiaire\DataBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    Ilcfrance\Passportstagiaire\DataBundle\Listener\CacheSubscriber:
        arguments: ["@logger", "@doctrine_mongodb.odm.default_document_manager", "@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

